before:
  hooks:
    - go mod tidy
builds:
- binary: '{{ .ProjectName }}'
  env:
    - CGO_ENABLED=0
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - '-s -w -X beryju.org/{{ .ProjectName }}/cmd.Version={{.Version}}'
  targets:
    - linux_arm_6
    - linux_arm_7
    - linux_arm64
    - linux_amd64
    - darwin_arm64
    - darwin_amd64
    - freebsd_arm64
    - freebsd_amd64
    - windows_arm64
    - windows_amd64
dockers:
- image_templates:
  - "ghcr.io/beryju/{{ .ProjectName }}:{{ .Version }}-amd64"
  use: buildx
  goarch: amd64
  build_flag_templates:
  - "--platform=linux/amd64"
- image_templates:
  - "ghcr.io/beryju/{{ .ProjectName }}:{{ .Version }}-arm64v8"
  use: buildx
  goarch: arm64
  build_flag_templates:
  - "--platform=linux/arm64/v8"
- image_templates:
  - "ghcr.io/beryju/{{ .ProjectName }}:{{ .Version }}-armv7"
  use: buildx
  goarch: arm
  goarm: "7"
  build_flag_templates:
  - "--platform=linux/arm/v7"
- image_templates:
  - "ghcr.io/beryju/{{ .ProjectName }}:{{ .Version }}-armv6"
  use: buildx
  goarch: arm
  goarm: "6"
  build_flag_templates:
  - "--platform=linux/arm/v6"
docker_manifests:
- name_template: ghcr.io/beryju/{{ .ProjectName }}:{{ .Version }}
  image_templates:
  - ghcr.io/beryju/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/beryju/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - ghcr.io/beryju/{{ .ProjectName }}:{{ .Version }}-armv7
  - ghcr.io/beryju/{{ .ProjectName }}:{{ .Version }}-armv6
- name_template: ghcr.io/beryju/{{ .ProjectName }}:v{{ .Major }}
  image_templates:
  - ghcr.io/beryju/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/beryju/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - ghcr.io/beryju/{{ .ProjectName }}:{{ .Version }}-armv7
  - ghcr.io/beryju/{{ .ProjectName }}:{{ .Version }}-armv6
- name_template: ghcr.io/beryju/{{ .ProjectName }}:latest
  image_templates:
  - ghcr.io/beryju/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/beryju/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - ghcr.io/beryju/{{ .ProjectName }}:{{ .Version }}-armv7
  - ghcr.io/beryju/{{ .ProjectName }}:{{ .Version }}-armv6
archives:
- id: raw
  format: binary
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}'
- id: tar
  format: tar.gz
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
brews:
  - ids:
      - raw
    tap:
      owner: beryju
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: goreleaser@beryju.org
    homepage: 'https://github.com/beryju/{{ .ProjectName }}'
    description: 'This is a small, golang-based OIDC Client, to be used in End-to-end or other testing.'
    folder: Formula
